23 Class_based_view/wesite/genericviews/urls.py
from django.conf.urls import url
from genericviews import views
app_name = 'genericviews'

urlpatterns = [
    path('', views.Indexview.as_view(), name='index'),
    path('(?<pk>[0-9]+)/',views.Detailsview.as_view(), name='details'),
    path('makeentry',views.makeentry.as_view(), name='makeentery'),
]

23 Class_based_view/wesite/wesite/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('genericviews/', include('genericviews.urls')),
]

23 Class_based_view/wesite/genericviews/models.py
from django.db import models

class person(models.Model):
    name = models.CharField(max_length=100)
    desc = models.CharField(max_length=300)
    def __str__(self):
        return self.name

23 Class_based_view/wesite/genericviews/forms.py
from django import forms

class PersonForm(forms.Form):
    name = forms.CharField(widget=forms.TextInput(attrs={
        'class':'form-control', 'placeholder':'Enter Your name'}))
    desc = forms.CharField(widget=forms.TextInput(attrs={
        'class':'form-control', 'placeholder':'Enter your description'}))

23 Class_based_view/wesite/genericviews/views.py
from django.shortcuts import render
from django.views import generic
from genericviews.forms import PersonForm
from genericviews.models import person

def makeentry(request):
    if request.method=='POST':
        form = PersonForm(request.POST)
        if form.is_valid():
            name = request.POST.get('name','')
            desc = request.POST.get('desc','')
        Person=person(name = name, desc= desc)
        Person.save()
        form =PersonForm()
        return render(request,'genericviews/makeentery.html',{'form':form})
    else:
        form= PersonForm()
        return render(request,'genericviews/makeentery.html',{'form':form})

class Indexview(generic.ListView):
    context_object_name = 'list'
    template_name = 'genericviews/index.html'
    def get_queryset(self):
        return person.objects.all()


class Detailsview(generic.DetailView):
    model = person
    template_name = 'genericviews/details.html'

23 Class_based_view/wesite/templates/details.html
<h1>{{ person.name }}</h1>
<h3>{{ person.desc }}</h3>

23 Class_based_view/wesite/templates/index.html
{% if list %}
<h1>Person Details! </h1>
<ul>
    {% for person in list %}
    <li><a href="{% url 'genericviews:details', person.id %}"> {{ person.name }}</a> </li>
    {% end for %}
</ul>
{% else %}
<h3> No person found.</h3>
{% endif %}

23 Class_based_view/wesite/templates/makeentery.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Bootstrap Example</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
    <style>
        body{background-color: paleturquoise;}
        .container{background-color: antiquewhite; border-radius: 0px; margin-top: 40px;}
        form{border: 5px ; border-color: red;}
    </style>
</head>
<body>
<div class="container">
    <h1 class="text-center"> Plase make entries here.</h1>
    <div class="row">
        <div class="col-md-5">
            <form action="{%  url 'genericviews:makeentery' %}" method="post">
                {% csrf_token %}
                {{ form }}<br>
                <center><input type="submit" value="Submit"> </center>

            </form>
        </div>
    </div>
</div>


</body>